### PR TITLE
Update FR

### PR DESCRIPTION
**Pull request by Cybereric**
historic=icon is deprecated >>> https://wiki.openstreetmap.org/wiki/Deprecated_features
27 uses only

### CODE REVIEW

**Comment by plepe** [comment]
Thanks!

**Comment by Cybereric** [comment]
Hello,

I've sent you an email with ideas but I forgot to ask you about few untranslated tags :-/
- goods=     is it related to vehicle access restrictions ?
- horse=      same question
- foot=         same question
- service=    info about service roads ?
- food=        I don't see which category to link that :  restaurants ? shops ?

Best regards
Éric

**Comment by plepe** [comment]
* goods=, horse=, foot= are a form of access tags, see https://wiki.openstreetmap.org/wiki/Key:access
* service= is a difficult tag as it depends on other values, e.g. highway=service or railways or shops. See https://wiki.openstreetmap.org/wiki/Key:service
* food= seems to be an error

**Comment by plepe** [comment]
Btw, I think it would be more reasonable to open a new issue for this instead of replying to a random pull request ...

**Pull request merged**
