### PR TITLE
Add german translations

### PR DESCRIPTION
**Pull request by kruegercharles**
I've added quite a few german translations, but I didn't also add their descriptions. I hope it still helps.

### CODE REVIEW

**Comment by plepe** [comment]
Thanks a lot. There are a lot of strings, which are not in the translation file yet, but are widely used. It is good, that you contributed them.

Not adding a description is fine, I can create this automatically via script.

However, I see some problems with your contribution:
* Strings with `;`, e.g. `tag:amenity=bicycle_parking;car_sharing`. Multi-value tags are handled differently (via the function `tagTransList()`, which translates each value like "amenity=bicycle_parking" and "amenity=car_sharing" and will even enumerate them with the correct word for the language -> "Fahrradständer und Carsharing"), so this just adds unnecessary duplicates. Please do not add them.
* There are some very seldom used values, where I would dispute the validity, e.g. [amenity=health_facility](https://taginfo.openstreetmap.org/tags/amenity=health_facility) with only 46 uses. A good indication is, if there's a Wiki page for a tag. Please do not add them.
* Wrong usage of lifecycle tags, e.g. `amenity=construction:fast_food`, `tag:historic=razed:watermill`. Even if these would be legitimate tags (The correct tags would be "construction:amenity=fast_food", resp. "razed:historic=watermill"), the translation would be wrong ("Schnellimbiss", "Wassermühle" -> it should be something like "Schnellimbiss im Bau", "abgerissene Wassermühle"). Please don't add lifecycle tags.
* No need to add `craft=yes`, because there's a common translation `*=yes`.
* `historic=Ober-Piependorf` ???

Please fix those problems and come back, okay?

**Comment by plepe** [comment]
Do you know, that you can translate strings on [Weblate](https://hosted.weblate.org/projects/openstreetbrowser/)? I would suggest to use this.

It's not possible to add strings there, though.

**Comment by kruegercharles** [comment]
My use-case was: I've downloaded some data from OSM and then checked if there are german translations for every tag within that dataset. If not, I added the translations. I didn't check if those tags are common, therefore stuff like `historic=Ober-Piependorf`. 
If you only want tags with a certain number of uses than you can go through each and check this yourself or discard the PR.

I've removed every tag with a `;` and `craft=yes`, as you requested.

Hope this helps.

**Comment by plepe** [comment]
Okay, thank you. I will check usage of the tags and remove the more questionable. I guess, it will take some time until I can finish this.

Thanks for you contribution anyway, I see a lot of missing strings.

**Pull request closed without merging**
