### PR TITLE
Create pt-br.json

### PR DESCRIPTION
**Pull request by IgorEliezer**
Creating Portuguese (Brazil) translation for tags. Partial.

Also adds (after L637) `shop=travel_agency`, `shop=video_games` and `shop=perfumery`.

### CODE REVIEW

**Comment by plepe** [comment]
Shall I pull the changes right-away, or do you want to add more translations?

**Comment by plepe** [comment]
Oh, and by the way: It's very welcome when you add additional strings (like `shop=travel_agency`) :)

**Comment by IgorEliezer** [comment]
> do you want to add more translations?

There are more to come.

**Comment by plepe** [comment]
Ok. I'll wait :-)

**Comment by IgorEliezer** [comment]
Go ahead. :+1:

**Comment by plepe** [comment]
Thanks! It's already online :-)

**Pull request merged**
